rpcs:
  - httpEndpoint: https://
    wsEndpoint: wss://
    keepAlive: true
    disableRetryOnRateLimit: false
    commitment: processed
    useAsBlockhashSource: true
    useAsSimulationSource: true
    useAsGetMultipleAccountsSource: true
fees:
  - mints:
      - So11111111111111111111111111111111111111112
    fee: 5000
    minExtraAmount: 15000
  - mints:
      - mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So
      - bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HP3piy1
      - J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn
      - he1iusmfkpAdwvxLNGV8Y1iSbj4rUy6yMhEA3fotn9A
      - 7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj
      - 5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm
      - vSoLxydx6akxyMD9XEcPvGYNGq6Nn66oqVb3UkGkei7
      - jupSoLaHXQiZZTSfEWMTRRgpnyFm8f6sZdosWBjx93v
      - LSTxxxnJzKDFSLr4dUkPcmCf5VyryEqzPLz5j4bpxFp
      - 7Q2afV64in6N6SeZsAAB81TJzwDoD6zpqmHkzi9Dcavn
    fee: 5000
    minExtraAmount: 15000
forceEnableSimulation: true
forceDisableSimulation: false
pairs:
  - So11111111111111111111111111111111111111112
  - EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
  - Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB
  - USDH1SM1ojwWUga67PGrgFWUHibbjqMvuMaDkRJTgkX
  - 2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo
  - Ea5SjE2Y6yvCeW5dYTn7PYMuW5ikXkvbGdcmSnXeaLjS
  - BQcdHdAQW1hczDbBi9hiegXAR7A98Q9jx3X3iBBBDiq4
  - 2VhjJ9WxaGC3EZFwJG9BDUs9KxKCAjQY4vgd1qxgYWVg
  - A9mUU4qviSctJVPJdBJWkb28deg915LYJKrzQ19ji3FM
  - 7kbnvuGBxxj8AG9qp8Scn56muWGaRaFqxg1FsRp3PaFT
  - AhhdRu5YZdjVkKR3wbnUDaymVQL2ucjMQ63sZ3LFHsch
  - C4Kkr9NZU3VbyedcgutU6LKmi6MKz81sx6gRmk5pX519
  - J9BcrQfX4p9D1bvLzRNCbMDv8f44a9LFdeqNE4Yk2WMD
  - Dn4noZ5jgGfkntzcQSUZ8czkreiZ1ForXYoV2H8Dm7S1
  - EjmyN6qEC1Tf1JxiG1ae7UTJhUxSwk1TCWNWqxWV4J6o
  - 88881Hu2jGMfCs9tMu5Rr7Ah7WBNBuXqde4nR5ZmKYYy
  - 5RpUwQ8wtdPCZHhu6MERp2RGrpobsbZ6MH5dDHkUjs2
  - JEFFSQ3s8T3wKsvp4tnRAsUBW7Cqgnf8ukBZC4C8XBm1
  - DdFPRnccQqLD4zCHrBqdY95D6hvw6PLWp9DEXj1fLCL9
  - 8XSsNvaKU9FDhYWAv7Yc7qSNwuJSzVrXBNEk7AFiWF69
  - 6nuaX3ogrr2CaoAPjtaKHAoBNWok32BMcRozuf32s2QF
  - 8Yv9Jz4z7BUHP68dz8E8m3tMe6NKgpMUKn8KVqrPA6Fr
  - eqKJTf1Do4MDPyKisMYqVaUFpkEFAs3riGF3ceDH2Ca
  - Eh6XEPhSwoLv5wFApukmnaVSHQ6sAnoD9BmgmwQoN2sN
  - Ez2zVjw85tZan1ycnJ5PywNNxR6Gm4jbXQtZKyQNu3Lv
  - FCqfQSujuPxy6V42UvafBhsysWtEq1vhjfMN1PUbgaxA
  - E2VmbootbVCBkMNNxKQgCLMS1X3NoGMaYAsufaAsf7M
  - T8KdT8hDzNhbGx5sjpEUxepnbDB1TZoCa7vtC5JjsMw
  - AEUT5uFm1D575FVCoQd5Yq891FJEqkncZUbBFoFcAhTV
  - E77cpQ4VncGmcAXX16LHFFzNBEBb2U7Ar7LBmZNfCgwL
  - Bn113WT6rbdgwrm12UJtnmNqGqZjY4it2WoUQuQopFVn
  - FwEHs3kJEdMa2qZHv7SgzCiFXUQPEycEXksfBkwmS8gj
  - 5goWRao6a3yNC4d6UjMdQxonkCMvKBwdpubU3qhfcdf1
  - 8qJSyQprMC57TWKaYEmetUR3UUiTP2M3hXdcvFhkZdmv
  - DNhZkUaxHXYvpxZ7LNnHtss8sQgdAfd1ZYS1fB7LKWUZ
  - 9vMJfxuKxXBoEa7rM12mYLMwTacLMLDJqHozw96WQL8i
  - HzwqbKZw8HxMN6bF2yFZNrht3c2iXXzpKcFu7uBEDKtr
  - A1KLoBrKBde8Ty9qtNQUtq3C2ortoC3u7twggz7sEto6
  - DEkqHyPN7GMRJ5cArtQFAWefqbZb33Hyf6s5iCwjEonT
  - LSTxxxnJzKDFSLr4dUkPcmCf5VyryEqzPLz5j4bpxFp
  - mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So
  - bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HP3piy1
  - J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn
  - 7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj
  - mSoLKr8mcyYPVwa9L1aabeWcDjo9WQUK4eqkDkHu2CP
  - 5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm
  - vSoLxydx6akxyMD9XEcPvGYNGq6Nn66oqVb3UkGkei7
  - Comp4ssDzXcLeu2MnLuGNNFC4cmLPMng8qWHPvzAMU1h
  - BdZPG9xWrG3uFrx2KrUW1jT4tZ9VKPDWknYihzoPRJS3
  - 9EaLkQrbjmbbuZG9Wdpo8qfNUEjHATJFSycEmw6f1rGX
  - he1iusmfkpAdwvxLNGV8Y1iSbj4rUy6yMhEA3fotn9A
  - HUBsveNpjo5pWqNkH57QzxjQASdTVXcSK7bVKTSZtcSX
  - strng7mqqc1MBJJV6vMzYbEqnwVGvKKGKedeCvtktWA
  - picobAEvs6w7QEknPce34wAE4gknZA9v5tTonnmHYdX
  - gso1xA56hacfgTHTF4F7wN5r4jbnJsKh99vR595uybA
  - BonK1YhkXEGLZzwtcvRTip3gAL9nCeQD7ppZBLXhtTs
  - 7Q2afV64in6N6SeZsAAB81TJzwDoD6zpqmHkzi9Dcavn
  - GEJpt3Wjmr628FqXxTgxMce1pLntcPV4uFi8ksxMyPQh
  - Dso1bDeDjCQxTrWHqUUi63oBvV7Mdm6WaobLbQ7gnPQ
  - yso11zxLbHA3wBJ9HAtVu6wnesqz9A2qxnhxanasZ4N
  - LAinEtNLgpmCP9Rvsf5Hn8W6EhNiKLZQti1xfWMLy6X
  - LnTRntk2kTfWEY6cVB8K9649pgJbt6dJLS1Ns1GZCWg
  - jucy5XJ76pHVvtPZb5TKRcGQExkwit2P5s4vY8UzmpC
  - pWrSoLAhue6jUxUkbWgmEy5rD9VJzkFmvfTDV5KgNuu
  - CgnTSoL3DgY9SFHxcLj6CgCgKKoTBr6tp4CPAEWy25DE
  - edge86g9cVz87xcpKpy3J77vbp4wYd9idEV562CCntt
  - StPsoHokZryePePFV8N7iXvfEmgUoJ87rivABX7gaW6
  - BANXyWgPpa519e2MtQF1ecRbKYKKDMXPF1dyBxUq9NQG
  - sSo14endRuUbvQaJS3dq36Q829a3A6BEfoeeRGJywEh
  - ELSoL1owwMWQ9foMsutweCsMKbTPVBD9pFqxQGidTaMC
  - pumpkinsEq8xENVZE6QgTS93EN4r9iKvNxNALS1ooyp
  - phaseZSfPxTDBpiVb96H4XFSD8xHeHxZre5HerehBJG
  - st8QujHLPsX3d6HG9uQg9kJ91jFxUgruwsb1hyYXSNd
  - 7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs
  - 2FPyTwcZLUg1MDrwsyoP4D6s1tM7hAkHYRjkNb5w6Pxk
  - ZScHuTtqZukUrtZS43teTKGs2VqkKL8k4QCouR2n6Uo
  - 3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh
  - 6DNSN2BJsaPFdFFc1zP37kkeNe4Usc1Sqkzr9C9vPWcU
  - 9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E
  - AUrMpCDYYcPuHhyNX8gEEqbmDPFUpBpHrNW3vPeCFn5Z
  - KgV1GvrHQmRBY8sHQQeUKwTm2r2h8t4C8qt12Cw1HVE
  - 9gP2kCy3wA1ctvYWQk75guqXuHfrEomqydHLtcTCqiLa
  - Gz7VkD4MacbEB6yC5XD3HcumEiYx2EtDYYrfikGsvopG
  - EPeUFDgHRxs9xxEPVaL6kfGQvCon7jmAWKVUHuux1Tpz
  - J3NKxxXZcnNiMjKw9hYb2K4LUxgwB6t1FtPtQVsv3KFr
  - AGFEad2et2ZJif9jaGpdMixQqvW5i81aBdvKe7PHNfz3
  - HxhWkVpk5NS4Ltg5nij2G671CKXFRKPK8vy271Ub4uEK
  - PzuaVAUH2tfxGZcbBR6kMxeJsBngnsPLFotGJNCtcsd
  - xALGoH1zUfRmpCriy94qbfoMXHtK6NDnMKzT4Xdvgms
  - 27G8MtK7VtTcCHkpASjSDdkWWYfoqT6ggEuKidVJidD4
  - JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN
  - jupSoLaHXQiZZTSfEWMTRRgpnyFm8f6sZdosWBjx93v
  - JxxWsvm9jHt4ah7DT9NuLyVLYZcZLUdPD93PcPQ71Ka
  - AURYydfxJib1ZkTir1Jn1J9ECYUtjb6rKQVmtYaixWPP
  - SLNDpmoWTVADgEdndyvWzroNL7zSi1dF9PC3xHGtPwp
  - kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6
  - LFNTYraetVioAPnGJht4yNg2aUZFXR776cMeN9VMjXp
  - kiraZUmSnzgfVfhrdvNj6hxHFaPFTTUk8ioY98cbh6G
  - iotEVVZLEywoTn1QdwNPddxPWszn3zFhEot3MfL9fns
  - GyuP7chtXSRB6erApifBxFvuTtz94x3zQo3JdWofBTgy
  - BKipkearSqAUdNKa1WDstvcMjoPsSKBuNyvKDQDDu9WE
  - SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt
  - GDfnEsia2WLAW5t8yx2X5j2mkfA74i5kwGdDuZHt7XmG
  - AT79ReYU9XtHUTF5vM6Q4oa9K8w7918Fp5SU7G1MDMQY
  - METAewgxyPbgwsseH8T16a39CQ5VyVxZi9zXiDPY18m
  - TNSRxcUxoT9xBG3de7PiJyTDYu7kskLqcpddxnEJAS6
  - UPTx1d24aBWuRgwxVnFmX4gNraj3QGFzL3QqBgxtWQG
  - SNSNkV9zfG5ZKWQs6x4hxvBRV6s8SqMfSGCtECDvdMd
  - 4LLbsb5ReP3yEtYzmXewyGjcir5uXtKFURtaEUVC2AHs
  - GENEtH5amGSi8kHAtQoezp1XEXwZJ8vcuePYnXdKrMYz
  - z3dn17yLaGMKffVogeFHQ9zWVcXgqgf3PQnDsNs2g6M
  - EchesyfXePKdLtoiZSL8pBe8Myagyy8ZRqsACNCFGnvp
  - Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1
  - BLZEEuZUBVqFhj8adcCFPJvPVCiCyVmh3hkJMrU8KuJA
  - MNDEFzGvMt87ueuHvVU9VcTqsAP5b3fTGPsHuuPA5ey
  - MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac
  - SHARKSYJjqaNyxVfrpnBN9pjgkhwDhatnMyicWPnr1s
  - AZsHEMXd36Bj1EMNXhowJajpUXzrKcK57wW4ZGXVa7yR
  - 3f7wfg9yHLtGKvy75MmqsVT1ueTFoqyySQbusrX1YAQ4
  - SHDWyBxihqiCj6YekG2GUr7wqKLeLAMK1gHZck9pL6y
  - nosXBVoaCTtYdLvKY6Csb4AC8JCdQKKAaWYtx2ZMoo7
  - E1kvzJNxShvvWTrudokpzuc789vRiDXfXG3duCuY6ooE
  - BANXbTpN8U2cU41FjPxe2Ti37PiT5cCxLUKDQZuJeMMR
  - DubwWZNWiNGMMeeQHPnMATNj77YZPZSAz2WVR5WjLJqz
  - Eh1fXbAipe4k7CYR9UMb2bbWmBcpU3HcyX3LWuRVFBLz
  - REdaoGk6EcBVgXW7vHs9FnzWmkr3ba6eHRBBgEtLNWo
  - NFTUkR4u7wKxy9QLaX2TGvd9oZSWoMo4jqSJqdMb7Nk
  - oreoN2tQbHXVaZsr3pf66A48miqcBXCDJozganhEJgz
  - oreoU2P8bN6jkk3jbaiVxYnG1dCXcYxwhwyK9jSybcp
  - hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux
  - mb1eu7TzEc71KxDpsmsKoucSSuuoGLv1drys1oP2jh6
  - KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS
  - DriFtupJYLTosbwoN8koMbEYSx54aFAVLddWsbksjwg7
  - ZEUS1aR7aX8DFFJf5QjWj2ftDDdNTroMNGo8YoQm3Gq
  - HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3
  - 4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R
  - 85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ
  - ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx
  - poLisWXnNRwC6oBu1vHiuKQzFjGL4XDSu4g9qjz9qVk
  - HBB111SCo9jkCejsZfz8Ec8nH7T6THF8KEKSnvwT6XK6
  - WENWENvqqNya429ubCdR81ZmD69brwQaaBYY6p3LCpk
  - DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263
  - 6gx6Ph2ek73kF6EWDrG4GQ54pcLJB6CYpATuRyxKXumo
  - HhJpBhRRn4g56VsyLuT8DL5Bv31HkXqsrahTTUCZeZg4
  - 9gwTegFJJErDpWJKjPfLr2g2zrE3nL1v5zpwbtsk3c6P
  - EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm
  - H7ed7UgcLp3ax4X1CQ5WuWDn6d1pprfMMYiv5ejwLWWU
  - FU1q8vJpZNUrmqsciSjp8bAKKidGsLmouB8CBdf8TKQv
  - 3psH1Mj1f7yUfaD5gh6Zj7epE8hhrMkMETgv5TshQA4o
  - 7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr
  - 45EgCwcPXYagBC7KqBin4nCFgEZWN7f3Y6nACwxqMCWX
  - CQSzJzwW5H1oyWrp6QhfUKYYwyovbSiVDKnAxNfb1tJC
  - BoZoQQRAmYkr5iJhqo7DChAs7DPDwEZ5cv1vkYC9yzJG
  - EJPtJEDogxzDbvM8qvAsqYbLmPj5n1vQeqoAzj9Yfv3q
  - 7BgBvyjrZX1YKz4oh9mjb8ZScatkkwb8DzFx7LoiVkM3
  - 6D7NaB2xsLd7cauWu1wKk6KBsJohJmP2qZH9GEfVi5Ui
  - ukHH6c7mMyiWCf1b9pnWe25TSpkDDt3H5pQZgZ74J82
  - MEW1gQWJ3nEXg2qgERiKu7FAFj79PHvQVREQUzScPP5
  - DARpE2GaVrazeh6mopWXbTT1hV3EbNNvHrJMMqJXUm6i
  - jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL
  - orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE
  - Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
  - 7raHqUrZXAqtxFJ2wcmtpH7SQYLeN9447vD4KhZM7tcP
  - GsNzxJfFn6zQdJGeYsupJWzUAm57Ba7335mfhWvFiE9Z
  - 26KMQVgDUoB6rEfnJ51yAABWWJND8uMtpnQgsHQ64Udr
  - 6gnCPhXtLnUD76HjQuSYPENLSZdG8RvDB1pTLM5aLSJA
  - 5LafQUrVco6o7KMz42eqVEJ9LW31StPyGjeeu5sKoMtA
  - rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof
  - 947tEoG318GUmyjVYhraNRvWpMX7fpBTDQFBoJvSkSG3
  - BFpchrNVhyTRzMNAg9QkiZfRN2vqRBwcYoTX8qgkbDvm
  - GtDZKAqvMZMnti46ZewMiXCa4oXF4bZxwQPoKzXPFxZn
  - 6DSqVXg9WLTWgz6LACqxN757QdHe1sCqkUfojWmxWtok
  - 5z3EqYQo9HiCEs3R84RCDMu2n7anpDMxRhdK8PSWmrRC
  - 7jmaTFBooHkaSrBJDftu3LcK85KPtqWTCaFZCDxQV7ZW
  - 7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU
  - 8wXtPeU6557ETkp9WHFY1n1EcU6NxDvbAggHGsMYiHsB
  - 9jaZhJM6nMHTo4hY9DGabQ1HNuUWhJtm7js1fmKMVpkN
  - ENoD8J2J6wNHkcJkvVBkwq5JMiR1oNBfBZRkoHCQogyT
  - 63LfDmNb3MQ8mw9MtZ2To9bEA2M71kZUUGq5tiJxcqj9
  - 5qKDWkBejLtRh1UGFV7e58QEkdn2fRyH5ehVXqUYujNW
  - F3nefJBcejYbtdREjui1T9DPh5dBgpkKq7u2GAAMXs5B
  - Av6qVigkb7USQyPXJkUvAEm4f599WTRvd75PUWBA9eNm
  - 4vqYQTjmKjxrWGtbL2tVkbAU1EVAz9JwcYtd2VE3PbVU
  - DLUNTKRQt7CrpqSX1naHUYoBznJ9pvMP65uCeWQgYnRK
  - 8vCAUbxejdtaxn6jnX5uaQTyTZLmXALg9u1bvFCAjtx7
  - 7mmXL6Et4SbpDs2iXoZQ3oPEeXeAiyETxh1QjDNi5qnV
  - AmgUMQeqW8H74trc8UkKjzZWtxBdpS496wh4GLy2mCpo
  - HLptm5e6rTgh4EKgDpYFrnRHbjpkMyVdEeREEa2G7rf9
  - SCSuPPNUSypLBsV4darsrYNg4ANPgaGhKhsA3GmMyjz
  - bobaM3u8QmqZhY1HwAtnvze9DLXvkgKYk3td3t8MLva
  - 9Ttyez3xiruyj6cqaR495hbBkJU6SUWdV6AmQ9MvbyyS
  - 69kdRLyP5DTRkpHraaSZAQbWmAwzF9guKjZfzMXzcbAs
  - C98A4nkJXhpVZNAZdHUA95RpTF3T4whtQubL3YobiUX9
  - AkVt31h8vgji5wF4nVbq1QmBV5wBoe8JdSoDTkDhQwEw
  - 7DGJnYfJrYiP5CKBx6wpbu8F5Ya1swdFoesuCrAKCzZc
  - 3acxNNmfdKKZj9i35P4VDBFm74Ufdt8ojKWceVGynwC5
  - 5BKTP1cWao5dhr8tkKcfPW9mWkKtuheMEAU6nih2jSX
  - xxxxa1sKNGwFtw2kFn8XauW9xq8hBZ5kVtcSesTT9fW
  - 3Rcc6tMyS7ZEa29dxV4g3J5StorS9J1dn98gd42pZTk1
  - 5mbK36SZ7J19An8jFochhQS4of8g6BwUjbeCSxBSoWdp
  - NeonTjSjsuo3rexg9o6vHuMXw62f9V7zvmu8M8Zut44
  - 7obg932wg2A1oTZhrPzR4DSdhKbjXzKSfHTBo2Hu5EbP
  - 9nEqaUcb16sQ3Tn1psbkWqyhPdLmfHWjKGymREjsAgTE
  - PUPS8ZgJ5po4UmNDfqtDMCPP6M1KP3EEzG9Zufcwzrg
  - HTPHknF5rBNCuZ1qK3muJA6Yo1HEhZj722oSESJnPBiw
  - AMjzRn1TBQwQfNAjHFeBb7uGbbqbJB7FzXAnGgdFPk6K
  - 3S8qX1MsMqRbiwKg2cQyx7nis1oHMgaCuc9c4VfvVdPN
  - 4vMsoUT2BWatFweudnQM1xedRLfJgJ7hswhcpz4xgBTy
  - AFbX8oGjGpmVFywbVouvhQSRmiW2aR1mohfahi4Y2AdB
  - 7i5KKsX2weiTkry7jA4ZwSuXGhs5eJBEjY8vVxR4pfRx
  - 5Wsd311hY8NXQhkt9cWHwTnqafk7BGEbLu8Py3DSnPAr
  - EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q
  - 6CNHDCzD5RkvBWxxyokQQNQPjFWgoHF94D7BmC73X6ZK
tradeConfigs:
  - mints:
      - So11111111111111111111111111111111111111112
      - mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So
      - bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HP3piy1
      - J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn
      - 7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj
      - jupSoLaHXQiZZTSfEWMTRRgpnyFm8f6sZdosWBjx93v
      - he1iusmfkpAdwvxLNGV8Y1iSbj4rUy6yMhEA3fotn9A
      - 5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm
      - vSoLxydx6akxyMD9XEcPvGYNGq6Nn66oqVb3UkGkei7
      - LSTxxxnJzKDFSLr4dUkPcmCf5VyryEqzPLz5j4bpxFp
      - 7Q2afV64in6N6SeZsAAB81TJzwDoD6zpqmHkzi9Dcavn
    minAmount: 1000000
    maxAmount: 1000000000
    minAccounts: 50
    maxAccounts: 50
    tipPercentage: 25
    minJitoTip: 5000
    maxJitoTip: 5000
    sender: GRPC
    loopIterationDelayMs: 1
    shortenToNearestMint: true
  - mints:
      - So11111111111111111111111111111111111111112
      - mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So
      - bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HP3piy1
      - J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn
      - 7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj
      - jupSoLaHXQiZZTSfEWMTRRgpnyFm8f6sZdosWBjx93v
      - he1iusmfkpAdwvxLNGV8Y1iSbj4rUy6yMhEA3fotn9A
      - 5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm
      - vSoLxydx6akxyMD9XEcPvGYNGq6Nn66oqVb3UkGkei7
      - LSTxxxnJzKDFSLr4dUkPcmCf5VyryEqzPLz5j4bpxFp
    minAmount: 1000000
    maxAmount: 1000000000
    minAccounts: 50
    maxAccounts: 50
    tipPercentage: 22
    minJitoTip: 5000
    maxJitoTip: 5000
    sender: GRPC
    loopIterationDelayMs: 1
    shortenToNearestMint: true
  - mints:
      - So11111111111111111111111111111111111111112
      - mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So
      - bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HP3piy1
      - J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn
      - 7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj
      - jupSoLaHXQiZZTSfEWMTRRgpnyFm8f6sZdosWBjx93v
      - he1iusmfkpAdwvxLNGV8Y1iSbj4rUy6yMhEA3fotn9A
      - 5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm
      - vSoLxydx6akxyMD9XEcPvGYNGq6Nn66oqVb3UkGkei7
      - LSTxxxnJzKDFSLr4dUkPcmCf5VyryEqzPLz5j4bpxFp
      - 7Q2afV64in6N6SeZsAAB81TJzwDoD6zpqmHkzi9Dcavn
    minAmount: 1000000
    maxAmount: 3000000000
    minAccounts: 50
    maxAccounts: 50
    tipPercentage: 50
    minJitoTip: 3000
    maxJitoTip: 15000
    sender: GRPC
    loopIterationDelayMs: 1
    shortenToNearestMint: true
  - mints:
      - So11111111111111111111111111111111111111112
      - mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So
      - bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HP3piy1
      - J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn
      - 7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj
      - jupSoLaHXQiZZTSfEWMTRRgpnyFm8f6sZdosWBjx93v
      - he1iusmfkpAdwvxLNGV8Y1iSbj4rUy6yMhEA3fotn9A
      - 5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm
      - vSoLxydx6akxyMD9XEcPvGYNGq6Nn66oqVb3UkGkei7
      - LSTxxxnJzKDFSLr4dUkPcmCf5VyryEqzPLz5j4bpxFp
    minAmount: 1000000
    maxAmount: 4000000000
    minAccounts: 50
    maxAccounts: 50
    tipPercentage: 50
    minJitoTip: 3000
    maxJitoTip: 15000
    sender: GRPC
    loopIterationDelayMs: 1
    shortenToNearestMint: true
  - mints:
      - So11111111111111111111111111111111111111112
      - mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So
      - bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HP3piy1
      - J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn
      - 7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj
      - jupSoLaHXQiZZTSfEWMTRRgpnyFm8f6sZdosWBjx93v
      - he1iusmfkpAdwvxLNGV8Y1iSbj4rUy6yMhEA3fotn9A
      - 5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm
      - vSoLxydx6akxyMD9XEcPvGYNGq6Nn66oqVb3UkGkei7
      - LSTxxxnJzKDFSLr4dUkPcmCf5VyryEqzPLz5j4bpxFp
      - 7Q2afV64in6N6SeZsAAB81TJzwDoD6zpqmHkzi9Dcavn
    minAmount: 1000000
    maxAmount: 3000000000
    minAccounts: 50
    maxAccounts: 50
    tipPercentage: 50
    minJitoTip: 5000
    maxJitoTip: 25000
    sender: GRPC
    loopIterationDelayMs: 1
    shortenToNearestMint: true
  - mints:
      - So11111111111111111111111111111111111111112
      - mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So
      - bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HP3piy1
      - J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn
      - 7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj
      - jupSoLaHXQiZZTSfEWMTRRgpnyFm8f6sZdosWBjx93v
      - he1iusmfkpAdwvxLNGV8Y1iSbj4rUy6yMhEA3fotn9A
      - 5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm
      - vSoLxydx6akxyMD9XEcPvGYNGq6Nn66oqVb3UkGkei7
      - LSTxxxnJzKDFSLr4dUkPcmCf5VyryEqzPLz5j4bpxFp
    minAmount: 1000000
    maxAmount: 4000000000
    minAccounts: 50
    maxAccounts: 50
    tipPercentage: 50
    minJitoTip: 5000
    maxJitoTip: 25000
    sender: GRPC
    loopIterationDelayMs: 1
    shortenToNearestMint: true
  - mints:
      - So11111111111111111111111111111111111111112
    minAmount: 100000000
    maxAmount: 10000000000
    minAccounts: 50
    maxAccounts: 50
    tipPercentage: 50
    minJitoTip: 5000
    maxJitoTip: 100000
    sender: GRPC
    loopIterationDelayMs: 1
    shortenToNearestMint: false
  - mints:
      - So11111111111111111111111111111111111111112
    minAmount: 100000000
    maxAmount: 10000000000
    minAccounts: 50
    maxAccounts: 50
    tipPercentage: 50
    minJitoTip: 5000
    maxJitoTip: 100000
    sender: GRPC
    loopIterationDelayMs: 1
    shortenToNearestMint: false
computeUnitLimitBase: 1400000
computeUnitLimitStep: 25000
slippageA: 0
slippageB: 0
onlyDirectRoutesA: false
onlyDirectRoutesB: false
addressLookupTableAddresses:
  - G4fg3iDBMxVwpMrmdMAyBGnzWrTYPQ2vcNt18wE8NKwR
  - 2bJ8hkwNn7rXtCKWTUr9LcomQ9BStwrF5wSxcj5LPpy2
  - 41Tdqo55S8NthbDK3fJridi7zbBNVyGC8K1bfgxXg3mx
  - EQ7JwXqgrCKUhQ5FwG1wYioxoC3DG8VVGhSbQVMbBEX
  - ASrmTGZ37LoRiDiops7SDJZEWEM4ZeDcVrV11Vxj9qho
priceRandomiserDelayMs: 1
TARGET_ACCOUNTS: 100
jupiter:
  endpoint: http://192.168.100.1:8080
  restrictIntermediateTokens: false
jito:
  minTip: 1000
  maxTip: 15000
  maxTxPerSecondPerRegion: 25
  tipPercentage: 10
  regions:
    - amsterdam
    - frankfurt
cache:
  swapInfo: true
  maxCacheAgeMs: 604800000
  maxSimulationCacheAgeMs: 1000
  enabledCacheDexes: []
  clearTxTooLarge: false
defaultHeapSizeSplitArb: 65536
defaultHeapSize: 131072
heapSizeStep: 32768
splitArbOnly: false
